#spring.application.name=replayly-server
#spring.datasource.url=jdbc:h2:mem:replayly;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.h2.console.enabled=true
#app.security.jwt.secret=UmVwbGF5bHlEZW1vSnd0U2VjcmV0S2V5VGhhdElzTG9uZ0Vub3VnaEZvckhTMjU2
#app.security.jwt.expiration-seconds=3600


spring.application.name=Replayly-server

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

JWT_SECRET=${JWT_SECRET}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,https://replayly-client.vercel.app,https://*.vercel.app}
